server:
  port: 8080
spring:
  datasource:
    username: root
    password: 19970305Xx
    url: jdbc:mysql://localhost:3306/reddit_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver